### ISSUE TITLE
Unable to define `WHERE (fieldA, fieldB) > (?, ?)`

### ISSUE THREAD

**Issue by mniewrzal** [storj/dbx#9]
I was unable to find a way to define something like `SELECT * WHERE (fieldA, fieldB) > (?, ?)`

**Comment by egonelbre** [comment]
I didn't test but `orderby` together with `paged` might give you what you want.

**Comment by mniewrzal** [comment]
it looks that if fields are primary key doing just `paged` give what I needed:
```
read paged (
	select columnA, columnB
)
```

**Comment by mniewrzal** [comment]
Its still not possible to do custom `(fieldA, fieldB) > (?, ?)` but I'm closing this for now as I found what was looking for.
